AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  py-infra-process

  Sample SAM Template for py-infra-process

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        EC2_INSTANCE: '9999'
        DB_INSTANCE: 'axul'
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  StartRDSResources:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/rds/
      Handler: app.start
      Runtime: python3.9
      Policies:
        - arn:aws:iam::831117102174:policy/axul-db-handler
      Architectures:
        - x86_64

  StopRDSResources:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/rds/
      Handler: app.stop
      Runtime: python3.9
      Policies:
        - arn:aws:iam::831117102174:policy/axul-db-handler
      Architectures:
        - x86_64

  StartEC2Resources:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: app/ec2/
        Handler: app.start
        Runtime: python3.9
        Architectures:
          - x86_64

  StopEC2Resources:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/ec2/
      Handler: app.stop
      Runtime: python3.9
      Architectures:
        - x86_64